---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system
data:
  key: QVFDdy9wWmFZUkNRSUJBQTU1dmNrVUxuMER1aUtZSUFXQXRPbUE9PQ==
type:
  kubernetes.io/rbd
...
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: kube-system
data:
  key: QVFDaUhKZGE2bjBnSGhBQWppRGV3Q2tYekRwTGo1WlJ0cy8zbkE9PQo=
type:
  kubernetes.io/rbd
...
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: logging
data:
  key: QVFDaUhKZGE2bjBnSGhBQWppRGV3Q2tYekRwTGo1WlJ0cy8zbkE9PQo=
type:
  kubernetes.io/rbd
...
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: openshift-infra
data:
  key: QVFDaUhKZGE2bjBnSGhBQWppRGV3Q2tYekRwTGo1WlJ0cy8zbkE9PQo=
type:
  kubernetes.io/rbd
...
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: openshift-metrics
data:
  key: QVFDaUhKZGE2bjBnSGhBQWppRGV3Q2tYekRwTGo1WlJ0cy8zbkE9PQo=
type:
  kubernetes.io/rbd
...
